use core::option;



#[derive(Drop)]
pub enum Opcode {
    OP_0,
    OP_PUSHBYTES_1,
    OP_PUSHBYTES_2,
    OP_PUSHBYTES_3,
    OP_PUSHBYTES_4,
    OP_PUSHBYTES_5,
    OP_PUSHBYTES_6,
    OP_PUSHBYTES_7,
    OP_PUSHBYTES_8,
    OP_PUSHBYTES_9,
    OP_PUSHBYTES_10,
    OP_PUSHBYTES_11,
    OP_PUSHBYTES_12,
    OP_PUSHBYTES_13,
    OP_PUSHBYTES_14,
    OP_PUSHBYTES_15,
    OP_PUSHBYTES_16,
    OP_PUSHBYTES_17,
    OP_PUSHBYTES_18,
    OP_PUSHBYTES_19,
    OP_PUSHBYTES_20,
    OP_PUSHBYTES_21,
    OP_PUSHBYTES_22,
    OP_PUSHBYTES_23,
    OP_PUSHBYTES_24,
    OP_PUSHBYTES_25,
    OP_PUSHBYTES_26,
    OP_PUSHBYTES_27,
    OP_PUSHBYTES_28,
    OP_PUSHBYTES_29,
    OP_PUSHBYTES_30,
    OP_PUSHBYTES_31,
    OP_PUSHBYTES_32,
    OP_PUSHBYTES_33,
    OP_PUSHBYTES_34,
    OP_PUSHBYTES_35,
    OP_PUSHBYTES_36,
    OP_PUSHBYTES_37,
    OP_PUSHBYTES_38,
    OP_PUSHBYTES_39,
    OP_PUSHBYTES_40,
    OP_PUSHBYTES_41,
    OP_PUSHBYTES_42,
    OP_PUSHBYTES_43,
    OP_PUSHBYTES_44,
    OP_PUSHBYTES_45,
    OP_PUSHBYTES_46,
    OP_PUSHBYTES_47,
    OP_PUSHBYTES_48,
    OP_PUSHBYTES_49,
    OP_PUSHBYTES_50,
    OP_PUSHBYTES_51,
    OP_PUSHBYTES_52,
    OP_PUSHBYTES_53,
    OP_PUSHBYTES_54,
    OP_PUSHBYTES_55,
    OP_PUSHBYTES_56,
    OP_PUSHBYTES_57,
    OP_PUSHBYTES_58,
    OP_PUSHBYTES_59,
    OP_PUSHBYTES_60,
    OP_PUSHBYTES_61,
    OP_PUSHBYTES_62,
    OP_PUSHBYTES_63,
    OP_PUSHBYTES_64,
    OP_PUSHBYTES_65,
    OP_PUSHBYTES_66,
    OP_PUSHBYTES_67,
    OP_PUSHBYTES_68,
    OP_PUSHBYTES_69,
    OP_PUSHBYTES_70,
    OP_PUSHBYTES_71,
    OP_PUSHBYTES_72,
    OP_PUSHBYTES_73,
    OP_PUSHBYTES_74,
    OP_PUSHBYTES_75,
    OP_PUSHDATA1,
    OP_PUSHDATA2,
    OP_PUSHDATA3,
    OP_PUSHDATA4,
    OP_1NEGATE,
    OP_RESERVED,
    OP_1,
    OP_2,
    OP_3,
    OP_4,
    OP_5,
    OP_6,
    OP_7,
    OP_8,
    OP_9,
    OP_10,
    OP_11,
    OP_12,
    OP_13,
    OP_14,
    OP_15,
    OP_16,
    OP_NOP,
    OP_VER,
    OP_IF,
    OP_NOTIF,
    OP_VERIF,
    OP_VERNOTIF,
    OP_ELSE,
    OP_ENDIF,
    OP_VERIFY,
    OP_RETURN,
    OP_TOALTSTACK,
    OP_FORMALTSTACK,
    OP_2DROP,
    OP_2DUP,
    OP_3DUP,
    OP_2OVER,
    OP_2ROT,
    OP_2SWAP,
    OP_IFDUP,
    OP_DEPTH,
    OP_DROP,
    OP_DUP,
    OP_NIP,
    OP_OVER,
    OP_PICK,
    OP_ROLL,
    OP_ROT,
    OP_SWAP,
    OP_TUCK,
    OP_CAT,
    OP_SUBSTR,
    OP_LEFT,
    OP_RIGHT,
    OP_SIZE,
    OP_INVERT,
    OP_AND,
    OP_OR,
    OP_XOR,
    OP_EQUAL,
    OP_EQUALVERIFY,
    OP_RESERVED1,
    OP_RESERVED2,
    OP_1ADD,
    OP_1SUB,
    OP_2MUL,
    OP_2DIV,
    OP_NEGATE,
    OP_ABS,
    OP_NOT,
    OP_0NOTEQUAL,
    OP_ADD,
    OP_SUB,
    OP_MUL,
    OP_DIV,
    OP_MOD,
    OP_LSHIFT,
    OP_RSHIFT,
    OP_BOOLAND,
    OP_BOOLOR,
    OP_NUMEQUAL,
    OP_NUMEQUALVERIFY,
    OP_NUMNOTEQUAL,
    OP_LESSTHAN,
    OP_GREATERTHAN,
    OP_LESSTHANOREQUAL,
    OP_GREATERTHANOREQUAL,
    OP_MIN,
    OP_MAX,
    OP_WITHIN,
    OP_RIPEMD160,
    OP_SHA1,
    OP_SHA256,
    OP_HASH160,
    OP_HASH256,
    OP_CODESEPARATOR,
    OP_CHECKSIG,
    OP_CHECKSIGVERIFY,
    OP_CHECKMULTISIG,
    OP_CHECKMULTISIGVERIFY,
    OP_NOP1,
    OP_CHECKLOCKTIMEVERIFY,
    OP_CHECKSEQUENCEVERIFY,
    OP_NOP4,
    OP_NOP5,
    OP_NOP6,
    OP_NOP7,
    OP_NOP8,
    OP_NOP9,
    OP_NOP10,
    OP_CHECKSIGADD,
}

trait OpcodeTrait {
    fn value(ref self: Opcode) -> u8;
}

impl OpcodeIntoU8 of Into<Opcode, u8> {
    fn into(self: Opcode) -> u8 {
        match self {
            Opcode::OP_0                    => 0,
            Opcode::OP_PUSHBYTES_1          => 1,
            Opcode::OP_PUSHBYTES_2          => 2,
            Opcode::OP_PUSHBYTES_3          => 3,
            Opcode::OP_PUSHBYTES_4          => 4,
            Opcode::OP_PUSHBYTES_5          => 5,
            Opcode::OP_PUSHBYTES_6          => 6,
            Opcode::OP_PUSHBYTES_7          => 7,
            Opcode::OP_PUSHBYTES_8          => 8,
            Opcode::OP_PUSHBYTES_9          => 9,
            Opcode::OP_PUSHBYTES_10         => 10,
            Opcode::OP_PUSHBYTES_11         => 11,
            Opcode::OP_PUSHBYTES_12         => 12,
            Opcode::OP_PUSHBYTES_13         => 13,
            Opcode::OP_PUSHBYTES_14         => 14,
            Opcode::OP_PUSHBYTES_15         => 15,
            Opcode::OP_PUSHBYTES_16         => 16,
            Opcode::OP_PUSHBYTES_17         => 17,
            Opcode::OP_PUSHBYTES_18         => 18,
            Opcode::OP_PUSHBYTES_19         => 19,
            Opcode::OP_PUSHBYTES_20         => 20,
            Opcode::OP_PUSHBYTES_21         => 21,
            Opcode::OP_PUSHBYTES_22         => 22,
            Opcode::OP_PUSHBYTES_23         => 23,
            Opcode::OP_PUSHBYTES_24         => 24,
            Opcode::OP_PUSHBYTES_25         => 25,
            Opcode::OP_PUSHBYTES_26         => 26,
            Opcode::OP_PUSHBYTES_27         => 27,
            Opcode::OP_PUSHBYTES_28         => 28,
            Opcode::OP_PUSHBYTES_29         => 29,
            Opcode::OP_PUSHBYTES_30         => 30,
            Opcode::OP_PUSHBYTES_31         => 31,
            Opcode::OP_PUSHBYTES_32         => 32,
            Opcode::OP_PUSHBYTES_33         => 33,
            Opcode::OP_PUSHBYTES_34         => 34,
            Opcode::OP_PUSHBYTES_35         => 35,
            Opcode::OP_PUSHBYTES_36         => 36,
            Opcode::OP_PUSHBYTES_37         => 37,
            Opcode::OP_PUSHBYTES_38         => 38,
            Opcode::OP_PUSHBYTES_39         => 39,
            Opcode::OP_PUSHBYTES_40         => 40,
            Opcode::OP_PUSHBYTES_41         => 41,
            Opcode::OP_PUSHBYTES_42         => 42,
            Opcode::OP_PUSHBYTES_43         => 43,
            Opcode::OP_PUSHBYTES_44         => 44,
            Opcode::OP_PUSHBYTES_45         => 45,
            Opcode::OP_PUSHBYTES_46         => 46,
            Opcode::OP_PUSHBYTES_47         => 47,
            Opcode::OP_PUSHBYTES_48         => 48,
            Opcode::OP_PUSHBYTES_49         => 49,
            Opcode::OP_PUSHBYTES_50         => 50,
            Opcode::OP_PUSHBYTES_51         => 51,
            Opcode::OP_PUSHBYTES_52         => 52,
            Opcode::OP_PUSHBYTES_53         => 53,
            Opcode::OP_PUSHBYTES_54         => 54,
            Opcode::OP_PUSHBYTES_55         => 55,
            Opcode::OP_PUSHBYTES_56         => 56,
            Opcode::OP_PUSHBYTES_57         => 57,
            Opcode::OP_PUSHBYTES_58         => 58,
            Opcode::OP_PUSHBYTES_59         => 59,
            Opcode::OP_PUSHBYTES_60         => 60,
            Opcode::OP_PUSHBYTES_61         => 61,
            Opcode::OP_PUSHBYTES_62         => 62,
            Opcode::OP_PUSHBYTES_63         => 63,
            Opcode::OP_PUSHBYTES_64         => 64,
            Opcode::OP_PUSHBYTES_65         => 65,
            Opcode::OP_PUSHBYTES_66         => 66,
            Opcode::OP_PUSHBYTES_67         => 67,
            Opcode::OP_PUSHBYTES_68         => 68,
            Opcode::OP_PUSHBYTES_69         => 69,
            Opcode::OP_PUSHBYTES_70         => 70,
            Opcode::OP_PUSHBYTES_71         => 71,
            Opcode::OP_PUSHBYTES_72         => 72,
            Opcode::OP_PUSHBYTES_73         => 73,
            Opcode::OP_PUSHBYTES_74         => 74,
            Opcode::OP_PUSHBYTES_75         => 75,
            Opcode::OP_PUSHDATA1            => 76,
            Opcode::OP_PUSHDATA2            => 77,
            Opcode::OP_PUSHDATA3            => 78,
            Opcode::OP_PUSHDATA4            => 79,
            Opcode::OP_1NEGATE              => 80,
            Opcode::OP_RESERVED             => 81,
            Opcode::OP_1                    => 82,
            Opcode::OP_2                    => 83,
            Opcode::OP_3                    => 84,
            Opcode::OP_4                    => 85,
            Opcode::OP_5                    => 86,
            Opcode::OP_6                    => 87,
            Opcode::OP_7                    => 88,
            Opcode::OP_8                    => 89,
            Opcode::OP_9                    => 90,
            Opcode::OP_10                   => 91,
            Opcode::OP_11                   => 92,
            Opcode::OP_12                   => 93,
            Opcode::OP_13                   => 94,
            Opcode::OP_14                   => 95,
            Opcode::OP_15                   => 96,
            Opcode::OP_16                   => 97,
            Opcode::OP_NOP                  => 98,
            Opcode::OP_VER                  => 99,
            Opcode::OP_IF                   => 100,
            Opcode::OP_NOTIF                => 101,
            Opcode::OP_VERIF                => 102,
            Opcode::OP_VERNOTIF             => 103,
            Opcode::OP_ELSE                 => 104,
            Opcode::OP_ENDIF                => 105,
            Opcode::OP_VERIFY               => 106,
            Opcode::OP_RETURN               => 107,
            Opcode::OP_TOALTSTACK           => 108,
            Opcode::OP_FORMALTSTACK         => 109,
            Opcode::OP_2DROP                => 110,
            Opcode::OP_2DUP                 => 111,
            Opcode::OP_3DUP                 => 112,
            Opcode::OP_2OVER                => 113,
            Opcode::OP_2ROT                 => 114,
            Opcode::OP_2SWAP                => 115,
            Opcode::OP_IFDUP                => 116,
            Opcode::OP_DEPTH                => 117,
            Opcode::OP_DROP                 => 118,
            Opcode::OP_DUP                  => 119,
            Opcode::OP_NIP                  => 120,
            Opcode::OP_OVER                 => 121,
            Opcode::OP_PICK                 => 122,
            Opcode::OP_ROLL                 => 123,
            Opcode::OP_ROT                  => 124,
            Opcode::OP_SWAP                 => 125,
            Opcode::OP_TUCK                 => 126,
            Opcode::OP_CAT                  => 127,
            Opcode::OP_SUBSTR               => 128,
            Opcode::OP_LEFT                 => 129,
            Opcode::OP_RIGHT                => 130,
            Opcode::OP_SIZE                 => 131,
            Opcode::OP_INVERT               => 132,
            Opcode::OP_AND                  => 133,
            Opcode::OP_OR                   => 134,
            Opcode::OP_XOR                  => 135,
            Opcode::OP_EQUAL                => 136,
            Opcode::OP_EQUALVERIFY          => 137,
            Opcode::OP_RESERVED1            => 138,
            Opcode::OP_RESERVED2            => 139,
            Opcode::OP_1ADD                 => 140,
            Opcode::OP_1SUB                 => 141,
            Opcode::OP_2MUL                 => 142,
            Opcode::OP_2DIV                 => 143,
            Opcode::OP_NEGATE               => 144,
            Opcode::OP_ABS                  => 145,
            Opcode::OP_NOT                  => 146,
            Opcode::OP_0NOTEQUAL            => 147,
            Opcode::OP_ADD                  => 148,
            Opcode::OP_SUB                  => 149,
            Opcode::OP_MUL                  => 150,
            Opcode::OP_DIV                  => 151,
            Opcode::OP_MOD                  => 152,
            Opcode::OP_LSHIFT               => 153,
            Opcode::OP_RSHIFT               => 154,
            Opcode::OP_BOOLAND              => 155,
            Opcode::OP_BOOLOR               => 156,
            Opcode::OP_NUMEQUAL             => 157,
            Opcode::OP_NUMEQUALVERIFY       => 158,
            Opcode::OP_NUMNOTEQUAL          => 159,
            Opcode::OP_LESSTHAN             => 160,
            Opcode::OP_GREATERTHAN          => 161,
            Opcode::OP_LESSTHANOREQUAL      => 162,
            Opcode::OP_GREATERTHANOREQUAL   => 163,
            Opcode::OP_MIN                  => 164,
            Opcode::OP_MAX                  => 165,
            Opcode::OP_WITHIN               => 166,
            Opcode::OP_RIPEMD160            => 167,
            Opcode::OP_SHA1                 => 168,
            Opcode::OP_SHA256               => 169,
            Opcode::OP_HASH160              => 170,
            Opcode::OP_HASH256              => 171,
            Opcode::OP_CODESEPARATOR        => 172,
            Opcode::OP_CHECKSIG             => 173,
            Opcode::OP_CHECKSIGVERIFY       => 174,
            Opcode::OP_CHECKMULTISIG        => 175,
            Opcode::OP_CHECKMULTISIGVERIFY  => 176,
            Opcode::OP_NOP1                 => 177,
            Opcode::OP_CHECKLOCKTIMEVERIFY  => 178,
            Opcode::OP_CHECKSEQUENCEVERIFY  => 179,
            Opcode::OP_NOP4                 => 180,
            Opcode::OP_NOP5                 => 181,
            Opcode::OP_NOP6                 => 182,
            Opcode::OP_NOP7                 => 183,
            Opcode::OP_NOP8                 => 184,
            Opcode::OP_NOP9                 => 185,
            Opcode::OP_NOP10                => 186,
            Opcode::OP_CHECKSIGADD          => 187,
        }
    }
}
impl U8IntoOpcode of TryInto<u8, Opcode> {
    fn try_into(self: u8) -> Option<Opcode> {
        match self {
        0    =>   Option::Some(Opcode::OP_0),
        1    =>   Option::Some(Opcode::OP_PUSHBYTES_1),
        2    =>   Option::Some(Opcode::OP_PUSHBYTES_2),
        3    =>   Option::Some(Opcode::OP_PUSHBYTES_3),
        4    =>   Option::Some(Opcode::OP_PUSHBYTES_4),
        5    =>   Option::Some(Opcode::OP_PUSHBYTES_5),
        6    =>   Option::Some(Opcode::OP_PUSHBYTES_6),
        7    =>   Option::Some(Opcode::OP_PUSHBYTES_7),
        8    =>   Option::Some(Opcode::OP_PUSHBYTES_8),
        9    =>   Option::Some(Opcode::OP_PUSHBYTES_9),
        10   =>   Option::Some(Opcode::OP_PUSHBYTES_10),
        11   =>   Option::Some(Opcode::OP_PUSHBYTES_11),
        12   =>   Option::Some(Opcode::OP_PUSHBYTES_12),
        13   =>   Option::Some(Opcode::OP_PUSHBYTES_13),
        14   =>   Option::Some(Opcode::OP_PUSHBYTES_14),
        15   =>   Option::Some(Opcode::OP_PUSHBYTES_15),
        16   =>   Option::Some(Opcode::OP_PUSHBYTES_16),
        17   =>   Option::Some(Opcode::OP_PUSHBYTES_17),
        18   =>   Option::Some(Opcode::OP_PUSHBYTES_18),
        19   =>   Option::Some(Opcode::OP_PUSHBYTES_19),
        20   =>   Option::Some(Opcode::OP_PUSHBYTES_20),
        21   =>   Option::Some(Opcode::OP_PUSHBYTES_21),
        22   =>   Option::Some(Opcode::OP_PUSHBYTES_22),
        23   =>   Option::Some(Opcode::OP_PUSHBYTES_23),
        24   =>   Option::Some(Opcode::OP_PUSHBYTES_24),
        25   =>   Option::Some(Opcode::OP_PUSHBYTES_25),
        26   =>   Option::Some(Opcode::OP_PUSHBYTES_26),
        27   =>   Option::Some(Opcode::OP_PUSHBYTES_27),
        28   =>   Option::Some(Opcode::OP_PUSHBYTES_28),
        29   =>   Option::Some(Opcode::OP_PUSHBYTES_29),
        30   =>   Option::Some(Opcode::OP_PUSHBYTES_30),
        31   =>   Option::Some(Opcode::OP_PUSHBYTES_31),
        32   =>   Option::Some(Opcode::OP_PUSHBYTES_32),
        33   =>   Option::Some(Opcode::OP_PUSHBYTES_33),
        34   =>   Option::Some(Opcode::OP_PUSHBYTES_34),
        35   =>   Option::Some(Opcode::OP_PUSHBYTES_35),
        36   =>   Option::Some(Opcode::OP_PUSHBYTES_36),
        37   =>   Option::Some(Opcode::OP_PUSHBYTES_37),
        38   =>   Option::Some(Opcode::OP_PUSHBYTES_38),
        39   =>   Option::Some(Opcode::OP_PUSHBYTES_39),
        40   =>   Option::Some(Opcode::OP_PUSHBYTES_40),
        41   =>   Option::Some(Opcode::OP_PUSHBYTES_41),
        42   =>   Option::Some(Opcode::OP_PUSHBYTES_42),
        43   =>   Option::Some(Opcode::OP_PUSHBYTES_43),
        44   =>   Option::Some(Opcode::OP_PUSHBYTES_44),
        45   =>   Option::Some(Opcode::OP_PUSHBYTES_45),
        46   =>   Option::Some(Opcode::OP_PUSHBYTES_46),
        47   =>   Option::Some(Opcode::OP_PUSHBYTES_47),
        48   =>   Option::Some(Opcode::OP_PUSHBYTES_48),
        49   =>   Option::Some(Opcode::OP_PUSHBYTES_49),
        50   =>   Option::Some(Opcode::OP_PUSHBYTES_50),
        51   =>   Option::Some(Opcode::OP_PUSHBYTES_51),
        52   =>   Option::Some(Opcode::OP_PUSHBYTES_52),
        53   =>   Option::Some(Opcode::OP_PUSHBYTES_53),
        54   =>   Option::Some(Opcode::OP_PUSHBYTES_54),
        55   =>   Option::Some(Opcode::OP_PUSHBYTES_55),
        56   =>   Option::Some(Opcode::OP_PUSHBYTES_56),
        57   =>   Option::Some(Opcode::OP_PUSHBYTES_57),
        58   =>   Option::Some(Opcode::OP_PUSHBYTES_58),
        59   =>   Option::Some(Opcode::OP_PUSHBYTES_59),
        60   =>   Option::Some(Opcode::OP_PUSHBYTES_60),
        61   =>   Option::Some(Opcode::OP_PUSHBYTES_61),
        62   =>   Option::Some(Opcode::OP_PUSHBYTES_62),
        63   =>   Option::Some(Opcode::OP_PUSHBYTES_63),
        64   =>   Option::Some(Opcode::OP_PUSHBYTES_64),
        65   =>   Option::Some(Opcode::OP_PUSHBYTES_65),
        66   =>   Option::Some(Opcode::OP_PUSHBYTES_66),
        67   =>   Option::Some(Opcode::OP_PUSHBYTES_67),
        68   =>   Option::Some(Opcode::OP_PUSHBYTES_68),
        69   =>   Option::Some(Opcode::OP_PUSHBYTES_69),
        70   =>   Option::Some(Opcode::OP_PUSHBYTES_70),
        71   =>   Option::Some(Opcode::OP_PUSHBYTES_71),
        72   =>   Option::Some(Opcode::OP_PUSHBYTES_72),
        73   =>   Option::Some(Opcode::OP_PUSHBYTES_73),
        74   =>   Option::Some(Opcode::OP_PUSHBYTES_74),
        75   =>   Option::Some(Opcode::OP_PUSHBYTES_75),
        76   =>   Option::Some(Opcode::OP_PUSHDATA1),
        77   =>   Option::Some(Opcode::OP_PUSHDATA2),
        78   =>   Option::Some(Opcode::OP_PUSHDATA3),
        79   =>   Option::Some(Opcode::OP_PUSHDATA4),
        80   =>   Option::Some(Opcode::OP_1NEGATE),
        81   =>   Option::Some(Opcode::OP_RESERVED),
        82   =>   Option::Some(Opcode::OP_1),
        83   =>   Option::Some(Opcode::OP_2),
        84   =>   Option::Some(Opcode::OP_3),
        85   =>   Option::Some(Opcode::OP_4),
        86   =>   Option::Some(Opcode::OP_5),
        87   =>   Option::Some(Opcode::OP_6),
        88   =>   Option::Some(Opcode::OP_7),
        89   =>   Option::Some(Opcode::OP_8),
        90   =>   Option::Some(Opcode::OP_9),
        91   =>   Option::Some(Opcode::OP_10),
        92   =>   Option::Some(Opcode::OP_11),
        93   =>   Option::Some(Opcode::OP_12),
        94   =>   Option::Some(Opcode::OP_13),
        95   =>   Option::Some(Opcode::OP_14),
        96   =>   Option::Some(Opcode::OP_15),
        97   =>   Option::Some(Opcode::OP_16),
        98   =>   Option::Some(Opcode::OP_NOP),
        99   =>   Option::Some(Opcode::OP_VER),
        100  =>   Option::Some(Opcode::OP_IF),
        101  =>   Option::Some(Opcode::OP_NOTIF),
        102  =>   Option::Some(Opcode::OP_VERIF),
        103  =>   Option::Some(Opcode::OP_VERNOTIF),
        104  =>   Option::Some(Opcode::OP_ELSE),
        105  =>   Option::Some(Opcode::OP_ENDIF),
        106  =>   Option::Some(Opcode::OP_VERIFY),
        107  =>   Option::Some(Opcode::OP_RETURN),
        108  =>   Option::Some(Opcode::OP_TOALTSTACK),
        109  =>   Option::Some(Opcode::OP_FORMALTSTACK),
        110  =>   Option::Some(Opcode::OP_2DROP),
        111  =>   Option::Some(Opcode::OP_2DUP),
        112  =>   Option::Some(Opcode::OP_3DUP),
        113  =>   Option::Some(Opcode::OP_2OVER),
        114  =>   Option::Some(Opcode::OP_2ROT),
        115  =>   Option::Some(Opcode::OP_2SWAP),
        116  =>   Option::Some(Opcode::OP_IFDUP),
        117  =>   Option::Some(Opcode::OP_DEPTH),
        118  =>   Option::Some(Opcode::OP_DROP),
        119  =>   Option::Some(Opcode::OP_DUP),
        120  =>   Option::Some(Opcode::OP_NIP),
        121  =>   Option::Some(Opcode::OP_OVER),
        122  =>   Option::Some(Opcode::OP_PICK),
        123  =>   Option::Some(Opcode::OP_ROLL),
        124  =>   Option::Some(Opcode::OP_ROT),
        125  =>   Option::Some(Opcode::OP_SWAP),
        126  =>   Option::Some(Opcode::OP_TUCK),
        127  =>   Option::Some(Opcode::OP_CAT),
        128  =>   Option::Some(Opcode::OP_SUBSTR),
        129  =>   Option::Some(Opcode::OP_LEFT),
        130  =>   Option::Some(Opcode::OP_RIGHT),
        131  =>   Option::Some(Opcode::OP_SIZE),
        132  =>   Option::Some(Opcode::OP_INVERT),
        133  =>   Option::Some(Opcode::OP_AND),
        134  =>   Option::Some(Opcode::OP_OR),
        135  =>   Option::Some(Opcode::OP_XOR),
        136  =>   Option::Some(Opcode::OP_EQUAL),
        137  =>   Option::Some(Opcode::OP_EQUALVERIFY),
        138  =>   Option::Some(Opcode::OP_RESERVED1),
        139  =>   Option::Some(Opcode::OP_RESERVED2),
        140  =>   Option::Some(Opcode::OP_1ADD),
        141  =>   Option::Some(Opcode::OP_1SUB),
        142  =>   Option::Some(Opcode::OP_2MUL),
        143  =>   Option::Some(Opcode::OP_2DIV),
        144  =>   Option::Some(Opcode::OP_NEGATE),
        145  =>   Option::Some(Opcode::OP_ABS),
        146  =>   Option::Some(Opcode::OP_NOT),
        147  =>   Option::Some(Opcode::OP_0NOTEQUAL),
        148  =>   Option::Some(Opcode::OP_ADD),
        149  =>   Option::Some(Opcode::OP_SUB),
        150  =>   Option::Some(Opcode::OP_MUL),
        151  =>   Option::Some(Opcode::OP_DIV),
        152  =>   Option::Some(Opcode::OP_MOD),
        153  =>   Option::Some(Opcode::OP_LSHIFT),
        154  =>   Option::Some(Opcode::OP_RSHIFT),
        155  =>   Option::Some(Opcode::OP_BOOLAND),
        156  =>   Option::Some(Opcode::OP_BOOLOR),
        157  =>   Option::Some(Opcode::OP_NUMEQUAL),
        158  =>   Option::Some(Opcode::OP_NUMEQUALVERIFY),
        159  =>   Option::Some(Opcode::OP_NUMNOTEQUAL),
        160  =>   Option::Some(Opcode::OP_LESSTHAN),
        161  =>   Option::Some(Opcode::OP_GREATERTHAN),
        162  =>   Option::Some(Opcode::OP_LESSTHANOREQUAL),
        163  =>   Option::Some(Opcode::OP_GREATERTHANOREQUAL),
        164  =>   Option::Some(Opcode::OP_MIN),
        165  =>   Option::Some(Opcode::OP_MAX),
        166  =>   Option::Some(Opcode::OP_WITHIN),
        167  =>   Option::Some(Opcode::OP_RIPEMD160),
        168  =>   Option::Some(Opcode::OP_SHA1),
        169  =>   Option::Some(Opcode::OP_SHA256),
        170  =>   Option::Some(Opcode::OP_HASH160),
        171  =>   Option::Some(Opcode::OP_HASH256),
        172  =>   Option::Some(Opcode::OP_CODESEPARATOR),
        173  =>   Option::Some(Opcode::OP_CHECKSIG),
        174  =>   Option::Some(Opcode::OP_CHECKSIGVERIFY),
        175  =>   Option::Some(Opcode::OP_CHECKMULTISIG),
        176  =>   Option::Some(Opcode::OP_CHECKMULTISIGVERIFY),
        177  =>   Option::Some(Opcode::OP_NOP1),
        178  =>   Option::Some(Opcode::OP_CHECKLOCKTIMEVERIFY),
        179  =>   Option::Some(Opcode::OP_CHECKSEQUENCEVERIFY),
        180  =>   Option::Some(Opcode::OP_NOP4),
        181  =>   Option::Some(Opcode::OP_NOP5),
        182  =>   Option::Some(Opcode::OP_NOP6),
        183  =>   Option::Some(Opcode::OP_NOP7),
        184  =>   Option::Some(Opcode::OP_NOP8),
        185  =>   Option::Some(Opcode::OP_NOP9),
        186  =>   Option::Some(Opcode::OP_NOP10),
        187  =>   Option::Some(Opcode::OP_CHECKSIGADD),
        _=> Option::None,
        }
    }
}

#[derive(Drop)]
pub enum ScriptElement {
    Opcode : Opcode,
    Value : ByteArray,
}

pub fn get_disabled_opcode() -> Span<u8> {
    let DISABLED_OPCODE: Array<u8> = array![126, 127, 128, 129, 130, 131, 132, 133, 134, 141, 142, 149, 150, 151, 152, 153];
    return DISABLED_OPCODE.span();
}
